name: my_server
description: An empty Aqueduct application.
version: 0.0.1

environment:
  sdk: ">=2.0.0 <3.0.0"

# dependency_overrides:
#   sqflite: ^2.0.0+2
publish_to: none

dependencies:
  sqflite_common: ^2.0.0+2
  sqflite_common_ffi: ^2.0.0
  aqueduct: ^4.0.0-b1

dev_dependencies:
  test: ^1.0.0
